# Generated by Django 4.0.3 on 2022-04-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_enrollment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=50)),
                ('Email', models.TextField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('employment', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('Experience', models.DecimalField(decimal_places=2, max_digits=3)),
                ('skillset', models.TextField(max_length=100)),
            ],
        ),
    ]
