# Generated by Django 4.0.3 on 2022-04-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_details_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment_details',
            name='enrollment_date',
            field=models.DateField(default='2022-01-22'),
            preserve_default=False,
        ),
    ]
