# Generated by Django 4.0.3 on 2022-04-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_enrollment_details_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='created_date',
            field=models.DateField(default='2022-04-12'),
            preserve_default=False,
        ),
    ]
