# Generated by Django 4.0.3 on 2022-04-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificate_details',
            fields=[
                ('certificate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_no', models.TextField(max_length=14)),
                ('qrcode', models.TextField(max_length=50)),
                ('username', models.TextField(max_length=100)),
                ('instructor', models.CharField(max_length=20)),
                ('issue_date', models.DateField()),
                ('validity_for', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('coupon_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coupon_code', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cousre_name', models.TextField(max_length=50)),
                ('course_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('video_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coursename', models.TextField(max_length=50)),
                ('video_link', models.TextField(max_length=500)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindash.course')),
            ],
        ),
        migrations.CreateModel(
            name='course_details',
            fields=[
                ('course_d_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_cost', models.TextField(max_length=50)),
                ('course_desc', models.TextField(max_length=100)),
                ('instructor', models.CharField(max_length=20)),
                ('duration', models.TimeField()),
                ('created_date', models.DateField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindash.course')),
            ],
        ),
        migrations.CreateModel(
            name='coupon_generation',
            fields=[
                ('coupon_g_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coupon_code', models.TextField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindash.coupon')),
            ],
        ),
    ]
